# Generated by Django 6.0.7 on 2026-09-15 12:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('postId', models.CharField(max_length=64)),
                ('userId', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('createdAt', models.BigIntegerField(default=api.models.current_time_ms)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('createdAt', models.BigIntegerField(default=api.models.current_time_ms)),
                ('userId', models.CharField(max_length=64)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
    ]
